artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion 
  database_name: predictive_maintenance_db
  collections:
    - telemetry
    - errors
    - failures
    - machines
    - maintenance
  raw_data_dir: artifacts/data_ingestion/raw_data


data_validation:
  root_dir: artifacts/data_validation    